# ps1-noise-0: learn hub / chapters — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-1: curriculum / build pipeline — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-2: markdown / deep playground — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-3: chapters ties back to manifest in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-4: assets / operating systems — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-5: techplus ties back to runtime bundle in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-6: security / lesson depth — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-7: kali / banner sync — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-8: pentest / depth metadata — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-9: gimkit / learn hub — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-10: build pipeline / kali — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-11: html polish / tokens — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-12: segments / quizzes — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-13: banners / cloud — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-14: tokens / threat model — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-15: css layers / normalize — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-16: study mode / html validation — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-17: deep playground / layout grid — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-18: freecodecamp / complete reference — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-19: comptia ties back to assets in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-20: lab procedures / html polish — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-21: quizzes / freecodecamp — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-22: tracks / editorial — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-23: split build ties back to hardware in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-24: manifest / path helpers — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-25: editorial / capstone — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-26: readability ties back to foreign ids in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-27: workplace ties back to org view in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-28: cloud / curriculum — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-29: networking ties back to pentest in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-30: database / css layers — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-31: operating systems / tracks — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-32: hardware / networking — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-33: peripherals / hands-on — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-34: continuity ties back to patch pass in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-35: threat model / pdf fixes — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-36: hands-on / playground wiring — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-37: markdown sources / checklist — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-38: runtime bundle / techplus — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-39: path helpers ties back to segments in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-40: chapter io ties back to comptia in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-41: audit scripts ties back to readability in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-42: normalize / peripherals — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-43: patch pass / chapter io — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-44: import graph / quiz bank — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-45: lesson depth ties back to consistency sweep in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-46: capstone / study patch — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-47: quiz bank / markdown — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-48: slow curriculum / gimkit — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-49: html validation / study mode — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-50: pdf fixes ties back to split build in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-51: voucher test / database — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-52: banner sync / markdown sources — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-53: foreign ids ties back to import graph in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-54: consistency sweep / voucher test — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-55: teach skin / courses map — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-56: layout grid / editorial standard — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-57: playground wiring / security — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-58: courses map / banners — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-59: depth metadata / lab procedures — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-60: org view / workplace — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-61: study patch / continuity — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-62: md chapter slice / audit scripts — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-63: complete reference ties back to slow curriculum in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-64: checklist / teach skin — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-65: editorial standard / md chapter slice — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-66: learn hub / chapters — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-67: curriculum / build pipeline — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-68: markdown / deep playground — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-69: chapters ties back to manifest in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-70: assets / operating systems — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-71: techplus ties back to runtime bundle in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-72: security / lesson depth — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-73: kali / banner sync — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-74: pentest / depth metadata — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-75: gimkit / learn hub — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-76: build pipeline / kali — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-77: html polish / tokens — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-78: segments / quizzes — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-79: banners / cloud — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-80: tokens / threat model — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-81: css layers / normalize — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-82: study mode / html validation — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-83: deep playground / layout grid — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-84: freecodecamp / complete reference — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-85: comptia ties back to assets in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-86: lab procedures / html polish — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-87: quizzes / freecodecamp — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-88: tracks / editorial — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-89: split build ties back to hardware in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-90: manifest / path helpers — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-91: editorial / capstone — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-92: readability ties back to foreign ids in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-93: workplace ties back to org view in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-94: cloud / curriculum — mental map while skimming (scripts/apply-techplus-readability-ps1.ps1)
# ps1-noise-95: networking ties back to pentest in this repo slice (scripts/apply-techplus-readability-ps1.ps1)
# Mirrors scripts/techplus-pdf-fixes.mjs for environments without Node.
# Run: powershell -File scripts/apply-techplus-readability-ps1.ps1

$ErrorActionPreference = "Stop"
$root = Split-Path -Parent $PSScriptRoot
$dirs = @(
  (Join-Path $root "content\techplus-chapters")
  "f:\TechPlus_Lessons"
)

# (from, to) — order: longer phrases before shorter substrings where needed
$pairs = @(
  @("Android quick set tings", "Android quick settings")
  @("iPhone Set tings", "iPhone Settings")
  @("Android Set tings", "Android Settings")
  @("iOS Set tings", "iOS Settings")
  @("Set tings", "Settings")
  @("end user' s", "end user's")
  @("manufacturer' s", "manufacturer's")
  @("website' s", "website's")
  @("network' s", "network's")
  @("customer' s", "customer's")
  @("computer' s", "computer's")
  @("Intel' s", "Intel's")
  @("HP' s", "HP's")
  @("wouldn' t", "wouldn't")
  @("couldn' t", "couldn't")
  @("shouldn' t", "shouldn't")
  @("doesn' t", "doesn't")
  @("haven' t", "haven't")
  @("hasn' t", "hasn't")
  @("hadn' t", "hadn't")
  @("wasn' t", "wasn't")
  @("weren' t", "weren't")
  @("isn' t", "isn't")
  @("aren' t", "aren't")
  @("didn' t", "didn't")
  @("don' t", "don't")
  @("Don' t", "Don't")
  @("won' t", "won't")
  @("can' t", "can't")
  @("it' s", "it's")
  @("It' s", "It's")
  @("that' s", "that's")
  @("That' s", "That's")
  @("there' s", "there's")
  @("There' s", "There's")
  @("here' s", "here's")
  @("Here' s", "Here's")
  @("what' s", "what's")
  @("What' s", "What's")
  @("Let' s", "Let's")
  @("USB- C", "USB-C")
  @("Wi- Fi", "Wi-Fi")
  @("A C power", "AC power")
  @("touc hpad", "touchpad")
  @("Bluetoothenabled", "Bluetooth-enabled")
  @("Computing Devicesand", "Computing Devices and")
  @("Self- Service ", "Self-Service ")
  @("third- party", "third-party")
  @("dotted- decimal", "dotted-decimal")
  @("inser tion", "insertion")
  @("Point stic k", "Point stick")
  @("Por trait", "Portrait")
  @("P asscode", "Passcode")
  @("Screen loc k", "Screen lock")
  @("K- loc k", "K-lock")
  @("loc k type", "lock type")
  @("set tings", "settings")
)

function Repair-TechPlusReadabilityText([string]$t) {
  foreach ($p in $pairs) {
    $t = $t.Replace($p[0], $p[1])
  }
  return $t
}

foreach ($dir in $dirs) {
  if (-not (Test-Path $dir)) { continue }
  Get-ChildItem $dir -Filter "*.md" | ForEach-Object {
    $raw = [System.IO.File]::ReadAllText($_.FullName)
    $after = Repair-TechPlusReadabilityText $raw
    if ($after -ne $raw) {
      [System.IO.File]::WriteAllText($_.FullName, $after)
      Write-Host "updated $($_.Name)"
    }
  }
}
Write-Host "done."
