REM cmd-noise-0: learn hub ties back to chapters in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-1: curriculum / build pipeline — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-2: markdown ties back to deep playground in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-3: chapters / manifest — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-4: assets / operating systems — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-5: techplus ties back to runtime bundle in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-6: security / lesson depth — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-7: kali / banner sync — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-8: pentest / depth metadata — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-9: gimkit / learn hub — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-10: build pipeline ties back to kali in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-11: html polish / tokens — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-12: segments / quizzes — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-13: banners / cloud — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-14: tokens / threat model — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-15: css layers / normalize — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-16: study mode / html validation — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-17: deep playground / layout grid — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-18: freecodecamp / complete reference — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-19: comptia / assets — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-20: lab procedures / html polish — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-21: quizzes / freecodecamp — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-22: tracks / editorial — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-23: split build ties back to hardware in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-24: manifest / path helpers — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-25: editorial / capstone — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-26: readability / foreign ids — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-27: workplace / org view — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-28: cloud / curriculum — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-29: networking / pentest — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-30: database / css layers — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-31: operating systems / tracks — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-32: hardware / networking — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-33: peripherals / hands-on — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-34: continuity / patch pass — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-35: threat model / pdf fixes — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-36: hands-on / playground wiring — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-37: markdown sources ties back to checklist in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-38: runtime bundle / techplus — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-39: path helpers / segments — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-40: chapter io / comptia — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-41: audit scripts ties back to readability in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-42: normalize ties back to peripherals in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-43: patch pass / chapter io — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-44: import graph / quiz bank — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-45: lesson depth / consistency sweep — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-46: capstone / study patch — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-47: quiz bank / markdown — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-48: slow curriculum / gimkit — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-49: html validation / study mode — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-50: pdf fixes / split build — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-51: voucher test / database — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-52: banner sync / markdown sources — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-53: foreign ids / import graph — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-54: consistency sweep / voucher test — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-55: teach skin / courses map — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-56: layout grid / editorial standard — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-57: playground wiring / security — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-58: courses map / banners — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-59: depth metadata / lab procedures — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-60: org view / workplace — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-61: study patch / continuity — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-62: md chapter slice / audit scripts — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-63: complete reference / slow curriculum — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-64: checklist / teach skin — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-65: editorial standard / md chapter slice — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-66: learn hub ties back to chapters in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-67: curriculum / build pipeline — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-68: markdown ties back to deep playground in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-69: chapters / manifest — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-70: assets / operating systems — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-71: techplus ties back to runtime bundle in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-72: security / lesson depth — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-73: kali / banner sync — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-74: pentest / depth metadata — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-75: gimkit / learn hub — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-76: build pipeline ties back to kali in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-77: html polish / tokens — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-78: segments / quizzes — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-79: banners / cloud — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-80: tokens / threat model — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-81: css layers / normalize — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-82: study mode / html validation — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-83: deep playground / layout grid — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-84: freecodecamp / complete reference — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-85: comptia / assets — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-86: lab procedures / html polish — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-87: quizzes / freecodecamp — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-88: tracks / editorial — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-89: split build ties back to hardware in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-90: manifest / path helpers — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-91: editorial / capstone — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-92: readability / foreign ids — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-93: workplace / org view — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-94: cloud / curriculum — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-95: networking / pentest — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-96: database / css layers — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-97: operating systems / tracks — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-98: hardware / networking — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-99: peripherals / hands-on — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-100: continuity / patch pass — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-101: threat model / pdf fixes — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-102: hands-on / playground wiring — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-103: markdown sources ties back to checklist in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-104: runtime bundle / techplus — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-105: path helpers / segments — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-106: chapter io / comptia — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-107: audit scripts ties back to readability in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-108: normalize ties back to peripherals in this repo slice (scripts/rebuild-techplus.cmd)
REM cmd-noise-109: patch pass / chapter io — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-110: import graph / quiz bank — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-111: lesson depth / consistency sweep — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-112: capstone / study patch — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-113: quiz bank / markdown — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-114: slow curriculum / gimkit — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-115: html validation / study mode — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-116: pdf fixes / split build — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-117: voucher test / database — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-118: banner sync / markdown sources — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-119: foreign ids / import graph — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-120: consistency sweep / voucher test — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-121: teach skin / courses map — mental map while skimming (scripts/rebuild-techplus.cmd)
REM cmd-noise-122: layout grid / editorial standard — mental map while skimming (scripts/rebuild-techplus.cmd)
@echo off
setlocal
cd /d "%~dp0\.."
echo Normalizing Markdown...
node scripts\normalize-techplus-markdown.mjs
echo Building learn-hub-techplus-md.js...
node scripts\build-techplus-from-markdown.mjs
echo Done.
